### ISSUE TITLE
About the store function

### ISSUE THREAD

**Issue by ismail-codar** [ccorcos/reactive-magic#2]
Hi @ccorcos  I see the code changed. Are you planning to complete remove the Store function or reimplement it?
Here is my experimental implementation https://github.com/ismail-codar/reactive-magic/blob/master/src/reactive.ts#L92 Sorry I do not understand why Constraint class is necessary. I hope documentation will be provided in the future.

**Comment by ccorcos** [comment]
> Are you planning to complete remove the Store function or reimplement it?

I don't think I'm going to implement the `Store` in the same way as before. Using define property was a little too magical for people to understand because it wasn't terribly clear when you were setting or getting a value. For example:

```js
const Points = Store({items: [{x:1, y:1}]})
Points.items.x += 1 // triggers a get but doesnt trigger a set!
```

The new way is a bit more explicit using `.set` and `.get` methods. Furthermore, instead of using `Store`, you can just create a class with reactive values as properties. An additional benefit here is that you can have prototype methods as well which tends to refactor nicely.

```js
class CounterStore {
  count = new Value(0)
  
  increment = () => {
    this.count.update(c => c + 1)
  }

  decrement = () => {
    this.count.update(c => c - 1)
  }
}
```

> Sorry I do not understand why Constraint class is necessary. I hope documentation will be provided in the future.

So the most important types to understand are `Settable` and `Gettable` and `Settable` is a superset of `Gettable`. A `Value` is `Settable` because you can `get` and `set` values with it. But some reactive variables are simply derived from others and cannot be `set`. For example a `DerivedValue` is a `Gettable`. `Value` and `DerivedValue` are typically going to be the only things you'll ever need.

`Constraint` is a little tricky and meant for advanced use cases. A `Constraint` is a way of making a `DerivedValue` `Settable` by providing a custom `set` function that is supposed to be the inverse of the get function. For example, you can derived the aspect ratio of an image from the height and the width:

```js
const height = new Value(10)
const width = new Value(20)
const aspectRatio = new DerivedValue(() => height.get() / width.get())
```

But what if you wanted to set the aspect ratio of the image? Maybe you want to give this variable to some kind of control knob that sets the value of the aspect ratio and you want everything else to react to it? That's where `Constraint` comes in:

```js
const aspectRatio = new Constraint({
	get: () => height.get() / width.get(),
	set: (v) => height.set(v * width.get()),
})
```

Both `Constraint` and `Value` are `Settable`. So when you're creating type definitions, make sure you specify the types using `Settable` and `Gettable` rather than `Value` because you might want to pass a `Constraint` instead.

I hope this helps -- let me know if you have any other questions :)

**Comment by ismail-codar** [comment]
It was very descriptive thanks much. 

I think Store function can be provide a syntactic sugar like utility. But users must know that Store function can be misleading.

User must know the restrictions and use it correctly.
```javascript
const Points = Store({items: [{x:1, y:1}]})
//Points.items.x += 1 // triggers a get but doesnt trigger a set!
Points.items = [{x:Points.items.x+1, y:1}] //may be good
````
Sugar is delicious. But it's never a good medicine in every way! Even so it should not be abandoned for the possibility of being harmful.

**Comment by ccorcos** [comment]
> Even so it should not be abandoned for the possibility of being harmful.

I disagree. If the harm can me eliminated early on, then why not? You are more than welcome to create your own Store function. Its pretty simple. But I don't want to encourage it...

**Comment by ccorcos** [comment]
Another reason is that I couldn't create a type signature for Store that was strict enough for my satisfaction. Here's my problem:

http://stackoverflow.com/questions/43768801/transforming-a-generic-interface-type-in-typescript

**Comment by ismail-codar** [comment]
Intellisense is working at this point.

![image](https://cloud.githubusercontent.com/assets/282104/25688681/f1ae44be-3089-11e7-9161-284c9a4f30ad.png)

**Comment by ccorcos** [comment]
Construct a store with a derived value tho

**Comment by ismail-codar** [comment]
I did some experiments now. 
I can see methods and public variables in my editor autocomplate showing normally. ExampleClass properties/methods and DerivedValue properties/methods.

````javascript
class ExampleClass<T> extends DerivedValue<T> {
  p:number = 0
};

const x = Store(new ExampleClass(() => mouse.get().x / size.get().width))
x.get()

**Comment by ismail-codar** [comment]
Currently seems Store function not working with DerivedValue in runtime. I misunderstood problem is not intellisense.
